'use client';

import { useState, useEffect, useRef } from 'react';

interface SyscallEntry {
  pid:     number;
  call:    string;
  args:    string;
  ret:     string;
  cat:     'net' | 'file' | 'fd' | 'mem' | 'proc';
  elapsed: string;
}

const BASE: SyscallEntry[] = [
  { pid: 14832, call: 'openat',   args: 'AT_FDCWD, "/etc/resolv.conf", O_RDONLY|O_CLOEXEC', ret: '3',  cat: 'file', elapsed: '0.000012' },
  { pid: 14832, call: 'read',     args: '3, "# Generated by resolvconf\\n...", 4096',         ret: '147', cat: 'fd',   elapsed: '0.000008' },
  { pid: 14832, call: 'close',    args: '3',                                                  ret: '0',  cat: 'fd',   elapsed: '0.000003' },
  { pid: 14832, call: 'socket',   args: 'AF_INET6, SOCK_STREAM|SOCK_CLOEXEC, IPPROTO_TCP',   ret: '4',  cat: 'net',  elapsed: '0.000015' },
  { pid: 14832, call: 'connect',  args: '4, {sa_family=AF_INET6, sin6_port=htons(443)}',      ret: '0',  cat: 'net',  elapsed: '0.000842' },
  { pid: 14832, call: 'sendto',   args: '4, "\\x16\\x03\\x01\\x02\\x00\\x01\\x00...", 517, MSG_NOSIGNAL', ret: '517', cat: 'net', elapsed: '0.000029' },
  { pid: 14832, call: 'recvfrom', args: '4, "\\x16\\x03\\x03\\x00J...", 16384, 0',            ret: '78', cat: 'net',  elapsed: '0.001203' },
  { pid: 14832, call: 'openat',   args: 'AT_FDCWD, "/proc/self/fd", O_RDONLY|O_DIRECTORY',   ret: '5',  cat: 'file', elapsed: '0.000021' },
  { pid: 14832, call: 'getdents64', args: '5, 0x7f3c12004000 /* 18 entries */, 32768',        ret: '488', cat: 'fd',  elapsed: '0.000011' },
  { pid: 14832, call: 'close',    args: '5',                                                  ret: '0',  cat: 'fd',   elapsed: '0.000004' },
  { pid: 14832, call: 'openat',   args: 'AT_FDCWD, "/app/.next/server/pages/_error.js", O_RDONLY', ret: '6', cat: 'file', elapsed: '0.000019' },
  { pid: 14832, call: 'fstat',    args: '6, {st_mode=S_IFREG|0644, st_size=14832}',           ret: '0',  cat: 'file', elapsed: '0.000007' },
  { pid: 14832, call: 'mmap',     args: 'NULL, 16384, PROT_READ|PROT_WRITE, MAP_PRIVATE|MAP_ANON', ret: '0x7f3c11000000', cat: 'mem', elapsed: '0.000013' },
  { pid: 14832, call: 'read',     args: '6, "\\x1f\\x8b\\x08\\x00\\x00\\x00\\x00\\x00...", 65536', ret: '14832', cat: 'fd', elapsed: '0.000044' },
  { pid: 14832, call: 'close',    args: '6',                                                  ret: '0',  cat: 'fd',   elapsed: '0.000003' },
  { pid: 14832, call: 'socket',   args: 'AF_UNIX, SOCK_STREAM|SOCK_CLOEXEC|SOCK_NONBLOCK, 0', ret: '7', cat: 'net', elapsed: '0.000009' },
  { pid: 14832, call: 'connect',  args: '7, {sa_family=AF_UNIX, sun_path="/var/run/redis/redis.sock"}', ret: '0', cat: 'net', elapsed: '0.000063' },
  { pid: 14832, call: 'write',    args: '7, "*3\\r\\n$3\\r\\nGET\\r\\n$12\\r\\nuser:session:...", 52', ret: '52', cat: 'fd', elapsed: '0.000011' },
  { pid: 14832, call: 'recvfrom', args: '7, "$85\\r\\n{\\\"id\\\":\\\"u_01J...\\\"}\\r\\n", 65536, 0', ret: '93', cat: 'net', elapsed: '0.000288' },
  { pid: 14832, call: 'close',    args: '7',                                                  ret: '0',  cat: 'fd',   elapsed: '0.000003' },
];

const LIVE: SyscallEntry[] = [
  { pid: 14832, call: 'epoll_wait', args: '8, [{EPOLLIN, {u32=4, u64=4}}], 1, 30000',        ret: '1',  cat: 'net',  elapsed: '0.029441' },
  { pid: 14832, call: 'recvfrom',   args: '4, "GET /api/health HTTP/1.1\\r\\n...", 65536, 0', ret: '142', cat: 'net', elapsed: '0.000018' },
  { pid: 14832, call: 'openat',     args: 'AT_FDCWD, "/app/logs/access.log", O_WRONLY|O_APPEND|O_CREAT', ret: '9', cat: 'file', elapsed: '0.000022' },
  { pid: 14832, call: 'write',      args: '9, "2030-05-13T08:14:03.441Z GET /api/health 200", 44', ret: '44', cat: 'fd', elapsed: '0.000009' },
  { pid: 14832, call: 'sendto',     args: '4, "HTTP/1.1 200 OK\\r\\nContent-Type: application/json\\r\\n...", 88', ret: '88', cat: 'net', elapsed: '0.000031' },
];

function callColor(cat: SyscallEntry['cat']): string {
  if (cat === 'net')  return '#a78bfa';
  if (cat === 'file') return '#67e8f9';
  if (cat === 'fd')   return '#60a5fa';
  if (cat === 'mem')  return '#fbbf24';
  return '#4ade80';
}

function retColor(ret: string): string {
  if (ret === '0')              return 'rgba(74,222,128,0.7)';
  if (ret.startsWith('0x'))     return '#a78bfa';
  if (ret.startsWith('-'))      return '#f87171';
  const n = parseInt(ret, 10);
  if (!isNaN(n) && n > 0)       return 'rgba(240,239,255,0.55)';
  return 'rgba(240,239,255,0.35)';
}

export default function StraceProcPanel() {
  const [revealed, setRevealed] = useState(0);
  const [live, setLive]         = useState<SyscallEntry[]>([]);
  const [liveIdx, setLiveIdx]   = useState(0);
  const ref     = useRef<HTMLDivElement>(null);
  const started = useRef(false);

  useEffect(() => {
    const el = ref.current;
    if (!el) return;
    const obs = new IntersectionObserver(
      ([entry]) => {
        if (entry.isIntersecting && !started.current) {
          started.current = true;
          setRevealed(1);
        }
      },
      { threshold: 0.1 },
    );
    obs.observe(el);
    return () => obs.disconnect();
  }, []);

  useEffect(() => {
    if (revealed === 0 || revealed > BASE.length) return;
    const id = setTimeout(() => setRevealed((r) => r + 1), 80);
    return () => clearTimeout(id);
  }, [revealed]);

  useEffect(() => {
    if (revealed <= BASE.length) return;
    const id = setInterval(() => {
      setLive((prev) => [...prev.slice(-4), LIVE[liveIdx % LIVE.length]]);
      setLiveIdx((i) => i + 1);
    }, 2600);
    return () => clearInterval(id);
  }, [revealed, liveIdx]);

  const allDone  = revealed > BASE.length;
  const displayed = BASE.slice(0, allDone ? BASE.length : revealed);
  const rows      = [...displayed, ...live];

  return (
    <div
      ref={ref}
      className="overflow-x-auto font-mono"
      style={{
        background:   'rgba(1,1,10,0.97)',
        border:       '1px solid rgba(255,255,255,0.07)',
        borderRadius: '3px',
        boxShadow:    '0 0 0 1px rgba(0,0,0,0.5), 0 16px 48px rgba(0,0,0,0.6)',
      }}
    >
      {/* Title bar */}
      <div
        className="flex items-center gap-3 px-4 py-2.5 select-none"
        style={{ borderBottom: '1px solid rgba(255,255,255,0.06)', background: 'rgba(255,255,255,0.02)' }}
      >
        <div className="flex items-center gap-1.5">
          <span className="w-2.5 h-2.5 rounded-full" style={{ background: '#FF5F57', boxShadow: '0 0 4px rgba(255,95,87,0.4)' }} />
          <span className="w-2.5 h-2.5 rounded-full" style={{ background: '#FFBD2E', boxShadow: '0 0 4px rgba(255,189,46,0.3)' }} />
          <span className="w-2.5 h-2.5 rounded-full" style={{ background: '#28C840', boxShadow: '0 0 4px rgba(40,200,64,0.3)' }} />
        </div>
        <span
          className="flex-1 text-center text-[9px] uppercase tracking-[0.2em]"
          style={{ color: 'rgba(255,255,255,0.22)' }}
        >
          construx@sys — strace -p 14832 -e trace=network,file
        </span>
        <span className="text-[8px] uppercase tracking-widest tabular-nums" style={{ color: allDone ? 'rgba(167,139,250,0.5)' : 'rgba(240,239,255,0.2)' }}>
          {allDone ? `pid 14832 · live` : 'attaching…'}
        </span>
      </div>

      {/* Shell prompt */}
      <div
        className="px-4 py-1.5 select-none"
        style={{ borderBottom: '1px solid rgba(255,255,255,0.04)', background: 'rgba(255,255,255,0.01)' }}
      >
        <span className="text-[9px]" style={{ color: 'rgba(74,222,128,0.45)' }}>construx@sys:~$</span>
        <span className="text-[9px] ml-2" style={{ color: 'rgba(240,239,255,0.22)' }}>
          strace -p 14832 -e trace=network,file -T -tt 2&gt;&amp;1
        </span>
      </div>

      {/* Attached line */}
      {revealed > 0 && (
        <div className="px-4 pt-2 pb-0.5">
          <span className="text-[8px]" style={{ color: 'rgba(167,139,250,0.55)' }}>
            strace: Process 14832 attached
          </span>
        </div>
      )}

      {/* Syscall rows */}
      <div className="px-4 py-2 space-y-0.5">
        {rows.map((entry, i) => (
          <div key={i} className="flex items-start gap-0 text-[8px] leading-[1.55]">
            <span style={{ color: 'rgba(240,239,255,0.18)', minWidth: '44px', flexShrink: 0 }}>
              [{entry.pid}]
            </span>
            <span style={{ color: callColor(entry.cat), minWidth: '88px', flexShrink: 0, fontWeight: 700 }}>
              {entry.call}
            </span>
            <span style={{ color: 'rgba(240,239,255,0.28)', flexShrink: 1, overflow: 'hidden', textOverflow: 'ellipsis', whiteSpace: 'nowrap', maxWidth: '340px' }}>
              ({entry.args})
            </span>
            <span style={{ color: 'rgba(240,239,255,0.18)', flexShrink: 0, marginLeft: '4px' }}>=</span>
            <span style={{ color: retColor(entry.ret), flexShrink: 0, marginLeft: '4px', minWidth: '60px' }}>
              {entry.ret}
            </span>
            <span style={{ color: 'rgba(240,239,255,0.15)', flexShrink: 0, marginLeft: '4px' }}>
              &lt;{entry.elapsed}&gt;
            </span>
          </div>
        ))}
        {allDone && (
          <div className="text-[8px] mt-1" style={{ color: 'rgba(167,139,250,0.35)' }}>
            ▌
          </div>
        )}
      </div>

      {/* Legend */}
      <div
        className="flex items-center gap-4 px-4 py-1.5 select-none"
        style={{ borderTop: '1px solid rgba(255,255,255,0.04)', background: 'rgba(255,255,255,0.01)' }}
      >
        {[
          ['net', '#a78bfa'],
          ['file', '#67e8f9'],
          ['fd', '#60a5fa'],
          ['mem', '#fbbf24'],
        ].map(([label, color]) => (
          <span key={label} className="flex items-center gap-1 text-[8px]">
            <span className="w-1.5 h-1.5 rounded-full inline-block" style={{ background: color }} />
            <span style={{ color: 'rgba(255,255,255,0.2)' }}>{label}</span>
          </span>
        ))}
      </div>

      {/* Footer */}
      <div
        className="flex items-center justify-between px-4 py-1.5 select-none"
        style={{ borderTop: '1px solid rgba(255,255,255,0.05)', background: 'rgba(0,0,4,0.5)' }}
      >
        <span className="text-[8px] uppercase tracking-widest" style={{ color: 'rgba(255,255,255,0.12)' }}>
          strace 6.7 · linux 6.8.4 · pid 14832 · construx-api
        </span>
        <span className="text-[8px] uppercase tracking-widest" style={{ color: allDone ? 'rgba(167,139,250,0.35)' : 'rgba(240,239,255,0.15)' }}>
          {allDone ? '● tracing' : 'loading'}
        </span>
      </div>
    </div>
  );
}
